### ISSUE TITLE
is Airrecord serializable?

### ISSUE THREAD

**Issue by iCueto** [sirupsen/airrecord#26]
There is a way to know if the result of a method is serializable? I need to do a Cache of the result.

I'm do it so:

```
def self.all_sorted
    Rails.cache.fetch("jobs|all_sorted", expires_in: 5.minutes) do
      all(sort: { "ID": "desc" })
    end
  end

  def self.find_and_cache(airtable_id, duration)
    Rails.cache.fetch("jobs|#{airtable_id}", expires_in: duration) do
      find(airtable_id)
    end
  end
```

But it's appear that do not  cache.

**Comment by sirupsen** [comment]
Hey, sorry for the delay.

Ah yes, that's correct, this test-case reproduces the problem:

```ruby
def test_serializable                                                                                                                                     
  stub_request([{"Name" => "omg", "Created" => Time.now.
  record = first_record                                                                                                                                   
  Marshal.dump(record)
end           
```

```
  1) Error:
TableTest#test_serializable:
TypeError: can't dump anonymous class #<Class:0x00007fcc25814d88>
    /Users/reading/src/airrecord/test/table_test.rb:328:in `dump'
    /Users/reading/src/airrecord/test/table_test.rb:328:in `test_serializable'
```

This is because we create anonymous classes for the ad-hoc API when you call `Airrecord.table` instead of creating a proper class yourself. You can fix this by creating `class Job < ActiveRecord::Base` and use this instead, or, you can implement `#marshal_dump` and `#marshal_load` on `ActiveRecord::Table` to support dumping it.
