### ISSUE TITLE
ArgumentError: tried to create Proc object without a block

### ISSUE THREAD

**Issue by sxh** [sirupsen/airrecord#47]
Using jruby-9.0.5.0 I get this error message immediately after issuing 'require "airrecord"' within irb.

**Comment by sirupsen** [comment]
What's the backtrace?

**Comment by sxh** [comment]
jruby-9.0.5.0 :001 > require 'airrecord'
ArgumentError: tried to create Proc object without a block
	from org/jruby/RubyKernel.java:1270:in `lambda'
	from /Users/steve.hayes/.rvm/gems/jruby-9.0.5.0/gems/airrecord-1.0.0/lib/airrecord/query_string.rb:29:in `<module:Encodings>'
	from /Users/steve.hayes/.rvm/gems/jruby-9.0.5.0/gems/airrecord-1.0.0/lib/airrecord/query_string.rb:22:in `<module:QueryString>'
	from /Users/steve.hayes/.rvm/gems/jruby-9.0.5.0/gems/airrecord-1.0.0/lib/airrecord/query_string.rb:9:in `<module:Airrecord>'
	from /Users/steve.hayes/.rvm/gems/jruby-9.0.5.0/gems/airrecord-1.0.0/lib/airrecord/query_string.rb:3:in `<top>'
	from org/jruby/RubyKernel.java:937:in `require'
	from /Users/steve.hayes/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from uri:classloader:/jruby/kernel/kernel.rb:1:in `(root)'
	from uri:classloader:/jruby/kernel/kernel.rb:13:in `<top>'
	from org/jruby/RubyKernel.java:937:in `require'
	from /Users/steve.hayes/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/steve.hayes/.rvm/gems/jruby-9.0.5.0/gems/airrecord-1.0.0/lib/airrecord/client.rb:2:in `<top>'
	from org/jruby/RubyKernel.java:937:in `require'
	from /Users/steve.hayes/.rvm/gems/jruby-9.0.5.0/gems/airrecord-1.0.0/lib/airrecord.rb:1:in `(root)'
	from /Users/steve.hayes/.rvm/gems/jruby-9.0.5.0/gems/airrecord-1.0.0/lib/airrecord.rb:5:in `<eval>'
	from org/jruby/RubyKernel.java:976:in `eval'
	from /Users/steve.hayes/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `(root)'
	from /Users/steve.hayes/.rvm/rubies/jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:128:in `require'
	from (irb):1:in `block in evaluate'
	from org/jruby/RubyKernel.java:1287:in `loop'
	from org/jruby/RubyKernel.java:1096:in `catch'
	from org/jruby/RubyKernel.java:1096:in `catch'
	from /Users/steve.hayes/.rvm/rubies/jruby-9.0.5.0/bin/irb:13:in `<top>'jruby-9.0.5.0 :002 >

**Comment by sirupsen** [comment]
Not sure why that'd happen, looks legit to me. Feel free to dig.

**Comment by chrisfrank** [comment]
Thanks for reporting this, @sxh. I can reproduce the error by running the test suite under `jruby-9.0.5.0`, which maps to CRuby 2.2. I cannot reproduce it under `jruby-9.1.0.0` (CRruby 2.3) or `jruby-9.2.4.0` (CRuby 2.5). If you can upgrade JRuby to 9.1 or 9.2, you should be all set.

@sirupsen do you want to commit to supporting Ruby 2.2, given that the Ruby core team no longer does? If so, I can make time to look into this further next week. Either way, I'd propose adding a [required_ruby_version](https://guides.rubygems.org/specification-reference/#required_ruby_version) to the gemspec before we close this issue.

**Comment by sxh** [comment]
Thanks for the update. I confirm that the problem does not reproduce under jruby-9.2.4.0, and I've not upgraded to that.

**Comment by sirupsen** [comment]
I'm fine with `required_ruby_version` 👍

**Comment by chrisfrank** [comment]
Thanks, everyone. This is patched in #49.
