### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by cantino** [sirupsen/airrecord#71]
I'm seeing 

```
.../faraday-1.0.0/lib/faraday/dependency_loader.rb:21: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
.../airrecord-1.0.5/lib/airrecord/faraday_rate_limiter.rb:9: warning: The called method `initialize' is defined here
```

when I use airrecord.

**Comment by sirupsen** [comment]
Those should be pretty easy to fix. Happy to accept a PR and make it into a patch release :)

**Comment by adamlwatson** [comment]
I'm having a breaking issue when attempting to upgrade to Ruby 3.2.2 because of this issue.

```
ArgumentError: wrong number of arguments (given 2, expected 1)
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/airrecord-1.0.12/lib/airrecord/faraday_rate_limiter.rb:9:in `initialize'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/dependency_loader.rb:21:in `new'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/dependency_loader.rb:21:in `new'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:57:in `build'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:175:in `block in to_app'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:174:in `each'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:174:in `inject'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:174:in `to_app'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:167:in `app'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:154:in `build_response'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/connection.rb:516:in `run_request'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/faraday-1.9.0/lib/faraday/connection.rb:281:in `post'
/Users/adamwatson/.rbenv/versions/3.2.2/gemsets/rostr/gems/airrecord-1.0.12/lib/airrecord/table.rb:80:in `records'
```

**Comment by Meekohi** [comment]
Anyone know if this is still an issue?
